# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160713_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sugar Access Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sugar Refresh Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='sugar_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sugar ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='sugar_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sugar Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
    ]
