# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        ('users', '0003_auto_20160719_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Instance'),
        ),
    ]
