# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160719_2226'),
    ]

    operations = [
    ]
