# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160720_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sugar_type',
            field=models.CharField(choices=[('normal', 'normal'), ('admin', 'admin')], default='normal', max_length=10, verbose_name='Sugar Type User'),
        ),
    ]
