# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_sugar_type'),
    ]

    operations = [
    ]
