# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='Sugar Url')),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, max_length=255, verbose_name='Client Secret')),
            ],
        ),
    ]
